### ISSUE TITLE
Stuck on joining lobby when already joined on IP

### ISSUE THREAD

**Issue by adam1lake** [feds01/durachok#41]
When attempting to join a lobby from the same IP address (any device on your LAN with the same IP address, not necessarily the same device), the game gets stuck on the joining lobby screen rather than displaying a useful error.

**Comment by feds01** [comment]
@adam1lake could you confirm that you weren't trying to join the game as a player, but as a spectator?

**Comment by adam1lake** [comment]
Correct, when joining as a player, it works as expected giving the option to enter a username then join the lobby.

**Comment by feds01** [comment]
Closing for now, will re-open if this can be confirmed.
